"""add_priority_column_v2

Revision ID: 5bac17ca857c
Revises: 84b4817b0297
Create Date: 2026-07-08 12:01:33.752608
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5bac17ca857c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odontogram_entries', sa.Column('priority', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odontogram_entries', 'priority')
    # ### end Alembic commands ###
